version: '3.1'

# The Database layer requires two services on its network
# Backend layer ony requires the backend image
services:
  db:                       # The db service is the postgres database
    build:
        context: ./pg-database
        dockerfile: Dockerfile
    image: keelah/pg_db     # Using our own image based on the postgres 14.1 alpine
    container_name: pg_db   #
    restart: always         # For security reasons, we restart it always
    environment:            # Basic env variables are set here
      POSTGRES_DB: db
      POSTGRES_USER: usr
    env_file:               # Passwords and sensitive data are set in an hidden env file
      - .env
    volumes:                # Data persistence is set via physical volume but could be switched to docker volumes
      - ./storage:/var/lib/postgresql/data

  adminer:                  # The adminer service uses the latest adminer image
    image: adminer
    container_name: adminer
    restart: always         # Just like the database, it should always restart
    ports:                  # The adminer is accessible via the http 8080 port
      - 8080:8080



  backend-1:                # The backend layer uses our own image built using maven 3.8.7 and eclipse-temurin 17 on alpine
    build:                  # THis is backend 1 for load balancing
        context: ./backend-api
        dockerfile: Dockerfile
    image: keelah/backend
    container_name: backend-1
    restart: always         # Like the rest, it restarts always
    ports:
      - 8181:8080           # We kept adminer so we are using 8181 for the API

  backend-2:                # The backend layer uses our own image built using maven 3.8.7 and eclipse-temurin 17 on alpine
    build:                  # This is backend 2 for load balancing
        context: ./backend-api
        dockerfile: Dockerfile
    image: keelah/backend
    container_name: backend-2
    restart: always         # Like the rest, it restarts always
    ports:
      - 8182:8080           # We kept adminer so we are using 8181 for the API


  oueb:                     # The web proxy layer uses the latest httpd image
    build:
        context: ./oueb
        dockerfile: Dockerfile
    image: keelah/oueb
    container_name: oueb    # ouèbe
    restart: unless-stopped 
    ports:
      - 80:80               # We still need to bind the port http