---
# tasks file for roles/api

# Start both API 
- name: Create API 1
  community.docker.docker_container:    # default script thingy
    name: backend-1                     # named
    image: keelah/backend               # img
    state: started                      # force start
    restart: true                       # restart if killed or crashed
    pull: true                          # force pull latest image
    networks:                           # network 
      - name: app-net
    ports:                              # port forward
      - "8181:8080"
  
- name: Create API 2
  community.docker.docker_container:
    name: backend-2
    image: keelah/backend
    state: started
    restart: true
    pull: true
    networks:
      - name: app-net
    ports:
      - "8182:8080"

- name: Create FONRT
  community.docker.docker_container:
    name: fonrt
    image: keelah/fonrt
    state: started
    restart: true
    pull: true
    env:
      VUE_APP_API_URL: thony.fain.takima.cloud/api
    networks:
      - name: app-net
    ports:
      - "90:80"

