---
# tasks file for roles/proxy


- name: Create PROXY
  community.docker.docker_container:
    name: oueb
    image: keelah/oueb
    state: started
    restart: true
    pull: true
    networks:
      - name: app-net
    ports:
      - "80:80"
